# Generated by Django 3.2 on 2022-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('icon_code', models.CharField(blank=True, help_text='Enter the icon code from https://remixicon.com like "ri-calculator-fill"', max_length=100, null=True)),
                ('color_code', models.CharField(blank=True, help_text='Enter your favorite icon color like "#29cc61"', max_length=100, null=True)),
            ],
        ),
    ]
